<a href="https://colab.research.google.com/github/irfangithubds/streamlit-example/blob/master/Diabetes_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# New Section

In [15]:
dds = pd.read_csv("Diabetes Dataset.csv")

In [16]:
dds.head()

Pregnancies  Glucose  Blood Pressure  Skin Thickness  Insulin  \
0            6      148              72              35        0   
1            1       85              66              29        0   
2            8      183              64               0        0   
3            1       89              66              23       94   
4            0      137              40              35      168   

   Body Mass Index)  Diabetes Pedigree Function  Age  Outcome  
0              33.6                       0.627   50        1  
1              26.6                       0.351   31        0  
2              23.3                       0.672   32        1  
3              28.1                       0.167   21        0  
4              43.1                       2.288   33        1

In [17]:
dds.rename(columns={"Body Mass Index)": "Body Mass Index"}, inplace=True)

In [18]:
dds.head()

Pregnancies  Glucose  Blood Pressure  Skin Thickness  Insulin  \
0            6      148              72              35        0   
1            1       85              66              29        0   
2            8      183              64               0        0   
3            1       89              66              23       94   
4            0      137              40              35      168   

   Body Mass Index  Diabetes Pedigree Function  Age  Outcome  
0             33.6                       0.627   50        1  
1             26.6                       0.351   31        0  
2             23.3                       0.672   32        1  
3             28.1                       0.167   21        0  
4             43.1                       2.288   33        1

In [19]:
dds.describe()

Pregnancies     Glucose  Blood Pressure  Skin Thickness     Insulin  \
count   768.000000  768.000000      768.000000      768.000000  768.000000   
mean      3.845052  120.894531       69.105469       20.536458   79.799479   
std       3.369578   31.972618       19.355807       15.952218  115.244002   
min       0.000000    0.000000        0.000000        0.000000    0.000000   
25%       1.000000   99.000000       62.000000        0.000000    0.000000   
50%       3.000000  117.000000       72.000000       23.000000   30.500000   
75%       6.000000  140.250000       80.000000       32.000000  127.250000   
max      17.000000  199.000000      122.000000       99.000000  846.000000   

       Body Mass Index  Diabetes Pedigree Function         Age     Outcome  
count       768.000000                  768.000000  768.000000  768.000000  
mean         31.992578                    0.471876   33.240885    0.348958  
std           7.884160                    0.331329   11.760232    0.476951  
min           0.000000                    0.078000   21.000000    0.000000  
25%          27.300000                    0.243750   24.000000    0.000000  
50%          32.000000                    0.372500   29.000000    0.000000  
75%          36.600000                    0.626250   41.000000    1.000000  
max          67.100000                    2.420000   81.000000    1.000000

In [20]:
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
dds_trData = dds.iloc[:,0:-1]

In [22]:
dds_trData.head()

Pregnancies  Glucose  Blood Pressure  Skin Thickness  Insulin  \
0            6      148              72              35        0   
1            1       85              66              29        0   
2            8      183              64               0        0   
3            1       89              66              23       94   
4            0      137              40              35      168   

   Body Mass Index  Diabetes Pedigree Function  Age  
0             33.6                       0.627   50  
1             26.6                       0.351   31  
2             23.3                       0.672   32  
3             28.1                       0.167   21  
4             43.1                       2.288   33

In [23]:
y = dds.Outcome
x = dds_trData

In [24]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [25]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=10)

In [26]:
from sklearn.preprocessing import MinMaxScaler

Scaler = MinMaxScaler()

norm_data = Scaler.fit_transform(x)

print(norm_data)

x = pd.DataFrame(norm_data, columns=x.columns)

[[0.35294118 0.74371859 0.59016393 ... 0.50074516 0.23441503 0.48333333]
 [0.05882353 0.42713568 0.54098361 ... 0.39642325 0.11656704 0.16666667]
 [0.47058824 0.91959799 0.52459016 ... 0.34724292 0.25362938 0.18333333]
 ...
 [0.29411765 0.6080402  0.59016393 ... 0.390462   0.07130658 0.15      ]
 [0.05882353 0.63316583 0.49180328 ... 0.4485842  0.11571307 0.43333333]
 [0.05882353 0.46733668 0.57377049 ... 0.45305514 0.10119556 0.03333333]]


In [27]:
x.head()

Pregnancies   Glucose  Blood Pressure  Skin Thickness   Insulin  \
0     0.352941  0.743719        0.590164        0.353535  0.000000   
1     0.058824  0.427136        0.540984        0.292929  0.000000   
2     0.470588  0.919598        0.524590        0.000000  0.000000   
3     0.058824  0.447236        0.540984        0.232323  0.111111   
4     0.000000  0.688442        0.327869        0.353535  0.198582   

   Body Mass Index  Diabetes Pedigree Function       Age  
0         0.500745                    0.234415  0.483333  
1         0.396423                    0.116567  0.166667  
2         0.347243                    0.253629  0.183333  
3         0.418778                    0.038002  0.000000  
4         0.642325                    0.943638  0.200000

In [28]:
# First Train the Model
from sklearn.linear_model import LogisticRegression
model_LR = LogisticRegression()
model_LR.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [29]:
# Now Predict the Model
y_predict_LR = model_LR.predict(x_test)

In [30]:
# Find Accuracy, Precision and Recall
print(accuracy_score(y_test,y_predict_LR ))
print(classification_report(y_test,y_predict_LR))

0.7402597402597403
              precision    recall  f1-score   support

           0       0.74      0.89      0.81       144
           1       0.73      0.49      0.59        87

    accuracy                           0.74       231
   macro avg       0.74      0.69      0.70       231
weighted avg       0.74      0.74      0.73       231



In [31]:
# Now find Confusion Matrix
confusion_matrix(y_test, y_predict_LR)

array([[128,  16],
       [ 44,  43]])

In [32]:
import numpy as np

In [33]:
input_data = (6, 144, 73, 189.6, 9.9, 66, 50, 99)

# Changing the input data into numpy array

input_data_into_np_arr = np.asarray(input_data)

# Reshape the array as we are predicting for one instance

input_data_reshaped = input_data_into_np_arr.reshape(1,-1)

prediction = model_LR.predict(input_data_reshaped)
print(prediction)

if (prediction[0] == 0):
    print("This person is not diabetic")
else:
    print("This person is diabetic")

[1]
This person is diabetic


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [34]:
#Saving the trained Model

import pickle

In [35]:
filename = 'trained.model.sav'
pickle.dump(model_LR, open(filename, 'wb'))

In [36]:
file_name = "trained_model.sav"

In [37]:
# loading the saved model
loaded_model = pickle.load(open('trained.model.sav', 'rb'))


In [38]:
input_data = (6, 144, 73, 189.6, 9.9, 66, 50, 99)

# Changing the input data into numpy array

input_data_into_np_arr = np.asarray(input_data)

# Reshape the array as we are predicting for one instance

input_data_reshaped = input_data_into_np_arr.reshape(1,-1)

prediction = model_LR.predict(input_data_reshaped)
print(prediction)

if (prediction[0] == 0):
    print("This person is not diabetic")
else:
    print("This person is diabetic")

[1]
This person is diabetic


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
